import { createFileRoute, Link } from '@tanstack/react-router'
import { ArrowLeft } from 'lucide-react'
import { FeedbackAccordion } from '@/components/quiz/FeedbackAccordion'
import { Furigana } from '@/components/verbs/Furigana'
import { parseFurigana } from '@/lib/data/furigana'

export const Route = createFileRoute('/cheatsheet/wearing')({
  component: WearingCheatsheetPage,
})

/**
 * One "way to say wear" row: the verb, what part of the body / kind of item
 * it goes with, and one example sentence. `exampleF` is the compact
 * furigana of `exampleJa`, generated by scripts/gen-wearing-furigana.ts and
 * verified there against expert-reviewed kana readings (one hand-fix: the
 * ヘルメット line, where kuromoji misread 被って as こうむって).
 */
interface WearRow {
  verb: string
  reading: string
  usedFor: string
  items: string
  exampleJa: string
  exampleF: string
  exampleEn: string
}

const WEAR_VERBS: WearRow[] = [
  {
    verb: '着る',
    reading: 'きる',
    usedFor: 'Torso & full body',
    items: 'shirts, jackets, dresses, kimono',
    exampleJa: '寒いのでコートを着た。',
    exampleF: '｜寒[さむ]いのでコートを｜着[き]た。',
    exampleEn: 'It was cold, so I put on a coat.',
  },
  {
    verb: '履く',
    reading: 'はく',
    usedFor: 'Waist down & feet',
    items: 'pants, skirts, shoes, socks',
    exampleJa: '新しい靴を履いて出かけた。',
    exampleF: '｜新[あたら]しい｜靴[くつ]を｜履[は]いて｜出[で]かけた。',
    exampleEn: 'I went out wearing my new shoes.',
  },
  {
    verb: '被る',
    reading: 'かぶる',
    usedFor: 'On the head',
    items: 'hats, caps, helmets, hoods',
    exampleJa: '自転車ではヘルメットを被ってください。',
    exampleF: '｜自転車[じてんしゃ]ではヘルメットを｜被[かぶ]ってください。',
    exampleEn: 'Please wear a helmet on a bicycle.',
  },
  {
    verb: 'かける',
    reading: 'かける',
    usedFor: 'Hooked over the ears',
    items: 'glasses, sunglasses',
    exampleJa: '父はいつも眼鏡をかけている。',
    exampleF: '｜父[ちち]はいつも｜眼鏡[めがね]をかけている。',
    exampleEn: 'My father always wears glasses.',
  },
  {
    verb: '羽織る',
    reading: 'はおる',
    usedFor: 'Draped over the shoulders',
    items: 'cardigans, coats, shawls',
    exampleJa: '肩にカーディガンを羽織った。',
    exampleF: '｜肩[かた]にカーディガンを｜羽織[はお]った。',
    exampleEn: 'I draped a cardigan over my shoulders.',
  },
  {
    verb: 'つける',
    reading: 'つける',
    usedFor: 'Attached to the body',
    items: 'earrings, necklaces, badges, watches, perfume',
    exampleJa: '今日は新しい香水をつけている。',
    exampleF: '｜今日[きょう]は｜新[あたら]しい｜香水[こうすい]をつけている。',
    exampleEn: "I'm wearing a new perfume today.",
  },
  {
    verb: 'はめる',
    reading: 'はめる',
    usedFor: 'Slipped snugly on',
    items: 'rings, gloves',
    exampleJa: '彼は結婚指輪をはめている。',
    exampleF: '｜彼[かれ]は｜結婚[けっこん]｜指輪[ゆびわ]をはめている。',
    exampleEn: 'He wears a wedding ring.',
  },
  {
    verb: '締める',
    reading: 'しめる',
    usedFor: 'Fastened around',
    items: 'neckties, belts, kimono obi',
    exampleJa: '面接のためにネクタイを締めた。',
    exampleF: '｜面接[めんせつ]のためにネクタイを｜締[し]めた。',
    exampleEn: 'I put on a tie for the interview.',
  },
  {
    verb: '巻く',
    reading: 'まく',
    usedFor: 'Wrapped around',
    items: 'scarves, mufflers',
    exampleJa: '寒い日はマフラーを巻く。',
    exampleF: '｜寒[さむ]い｜日[ひ]はマフラーを｜巻[ま]く。',
    exampleEn: 'I wrap a scarf around my neck on cold days.',
  },
  {
    verb: 'する',
    reading: 'する',
    usedFor: 'Everyday catch-all for accessories',
    items: 'masks, ties, rings, gloves, scarves',
    exampleJa: '電車ではマスクをしている人が多い。',
    exampleF: '｜電車[でんしゃ]ではマスクをしている｜人[ひと]が｜多[おお]い。',
    exampleEn: 'Many people wear masks on the train.',
  },
]

/** Small labeled card, same shape as the counters page's HowCard. */
function HowCard({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-lg border p-4">
      <div className="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
        {title}
      </div>
      <div className="mt-2 space-y-2 text-sm leading-relaxed">{children}</div>
    </div>
  )
}

function ExampleLine({ ja, en }: { ja: React.ReactNode; en: string }) {
  return (
    <div>
      <div lang="ja" className="text-base">
        {ja}
      </div>
      <div className="text-xs text-muted-foreground">{en}</div>
    </div>
  )
}

function WearingCheatsheetPage() {
  return (
    <div className="space-y-6">
      <div>
        <Link
          to="/cheatsheet"
          className="mb-2 inline-flex items-center gap-1 text-xs text-muted-foreground transition-colors duration-100 hover:text-foreground"
        >
          <ArrowLeft className="size-3.5" /> Cheatsheet
        </Link>
        <h1 className="text-2xl font-semibold">Ways to Say &ldquo;Wear&rdquo;</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          English wears everything; Japanese picks the verb by <em>where on
          the body</em> the item goes and <em>how it attaches</em> — clothes
          are <span lang="ja">着る</span> on the torso but{' '}
          <span lang="ja">履く</span> from the waist down, glasses hook on
          (<span lang="ja">かける</span>), hats go on top
          (<span lang="ja">かぶる</span>). The table below covers the verbs
          daily life needs.
        </p>
      </div>

      <section>
        <h2 className="mb-3 text-lg font-semibold">How Wearing Works</h2>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
          <HowCard title="The pattern">
            <ExampleLine
              ja={
                <>
                  シャツ<span className="font-semibold">を</span>
                  <ruby>着<rt>き</rt></ruby>る
                </>
              }
              en="item + を + the verb matched to the item"
            />
            <ExampleLine
              ja={
                <>
                  <ruby>帽子<rt>ぼうし</rt></ruby>
                  <span className="font-semibold">を</span>かぶる
                </>
              }
              en="put on a hat"
            />
          </HowCard>
          <HowCard title="Putting on vs wearing">
            <ExampleLine
              ja={
                <>
                  コートを
                  <span className="font-semibold">
                    <ruby>着<rt>き</rt></ruby>る
                  </span>
                </>
              }
              en="the plain verb is the ACTION of putting it on"
            />
            <ExampleLine
              ja={
                <>
                  コートを
                  <span className="font-semibold">
                    <ruby>着<rt>き</rt></ruby>ている
                  </span>
                </>
              }
              en="〜ている is the STATE of having it on — “is wearing”"
            />
          </HowCard>
          <HowCard title="Not sure which verb?">
            <ExampleLine
              ja={
                <>
                  ネクタイ・マスク・<ruby>指輪<rt>ゆびわ</rt></ruby>＋
                  <span className="font-semibold">を</span>する
                </>
              }
              en="する covers most accessories in everyday speech"
            />
            <ExampleLine
              ja={
                <>
                  <ruby>身<rt>み</rt></ruby>につける
                </>
              }
              en="a formal catch-all for anything worn or carried on the body"
            />
          </HowCard>
        </div>
      </section>

      <section>
        <h2 className="mb-3 text-lg font-semibold">The Verbs, by Body Part</h2>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[46rem] border-collapse text-sm">
            <thead>
              <tr className="border-b text-left text-xs text-muted-foreground">
                <th className="py-1.5 pr-3 font-medium">Verb</th>
                <th className="py-1.5 pr-3 font-medium">Reading</th>
                <th className="py-1.5 pr-3 font-medium">Where / how</th>
                <th className="py-1.5 pr-3 font-medium">Typical items</th>
                <th className="py-1.5 font-medium">Example</th>
              </tr>
            </thead>
            <tbody>
              {WEAR_VERBS.map((row) => (
                <tr key={row.verb + row.usedFor} className="border-b border-border/60">
                  <td lang="ja" className="py-2.5 pr-3 text-lg whitespace-nowrap">
                    {row.verb}
                  </td>
                  <td lang="ja" className="py-2.5 pr-3 text-muted-foreground">
                    {row.reading}
                  </td>
                  <td className="py-2.5 pr-3">{row.usedFor}</td>
                  <td className="py-2.5 pr-3 text-muted-foreground">{row.items}</td>
                  <td className="py-2.5">
                    <div className="text-base/loose">
                      <Furigana
                        segments={parseFurigana(row.exampleF)}
                        className="whitespace-normal"
                      />
                    </div>
                    <div className="text-xs text-muted-foreground">{row.exampleEn}</div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section>
        <h2 className="mb-3 text-lg font-semibold">Watch Out</h2>
        <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed">
          <li>
            <span lang="ja">履く</span> for pants and skirts is often written{' '}
            <span lang="ja">穿く</span> in careful writing (feet get{' '}
            <span lang="ja">履く</span>, waist-down cloth gets{' '}
            <span lang="ja">穿く</span>) — but in practice it&apos;s usually
            just kana: <span lang="ja">ズボンをはく</span>.
          </li>
          <li>
            Describing what someone <em>has on</em> almost always takes{' '}
            <span lang="ja">〜ている</span>:{' '}
            <span lang="ja">眼鏡をかけている人</span> &ldquo;the person
            wearing glasses&rdquo;, <span lang="ja">スーツを着ている</span>{' '}
            &ldquo;is wearing a suit&rdquo;. The plain form usually reads as
            the act of putting on (or a habit).
          </li>
          <li>
            Taking things off splits the same way:{' '}
            <span lang="ja"><ruby>脱<rt>ぬ</rt></ruby>ぐ</span> undoes
            clothing — <span lang="ja">着る・履く</span> items and, together
            with <span lang="ja"><ruby>取<rt>と</rt></ruby>る</span>, hats —
            while <span lang="ja"><ruby>外<rt>はず</rt></ruby>す</span>{' '}
            removes accessories: glasses, rings, ties, watches.
          </li>
          <li>
            <span lang="ja">かける</span> is for things that hook or hang —
            in everyday speech that means glasses. Necklaces are usually{' '}
            <span lang="ja">つける</span> or <span lang="ja">する</span>.
          </li>
        </ul>
        <div className="mt-3">
          <FeedbackAccordion title="Trivia: wearing a cat">
            <p className="text-sm leading-relaxed">
              <span lang="ja">
                <ruby>猫<rt>ねこ</rt></ruby>を<ruby>被<rt>かぶ</rt></ruby>る
              </span>{' '}
              (&ldquo;to wear a cat&rdquo;) means putting on an innocent,
              well-behaved front — the metaphor is covering your real self
              with something soft and harmless, the same{' '}
              <span lang="ja">被る</span> you use for hats.
            </p>
          </FeedbackAccordion>
        </div>
      </section>

      <p className="text-xs text-muted-foreground">
        Cross-checked against{' '}
        <a
          className="text-primary underline-offset-2 hover:underline"
          href="https://maggiesensei.com/2010/09/15/%E7%9D%80%E3%82%8Bkiru-how-to-say-wear-or-put-on-in-japanese/"
          target="_blank"
          rel="noreferrer"
        >
          Maggie Sensei
        </a>{' '}
        and{' '}
        <a
          className="text-primary underline-offset-2 hover:underline"
          href="https://kuwashiijapanese.com/2020/07/08/the-many-ways-to-wear-and-take-off-something-in-japanese/"
          target="_blank"
          rel="noreferrer"
        >
          Kuwashii Japanese
        </a>
        &apos;s guides to wearing verbs.
      </p>
    </div>
  )
}
