/**
 * Prepare the pinned PaddleOCR.js worker/runtime and verify the committed
 * PP-OCRv5 model archives. All downloadable files are gzip containers;
 * the browser verifies them, inflates them into Cache Storage, then the
 * service worker exposes their ordinary target URLs to the OCR worker.
 */
import { createHash } from 'node:crypto'
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { basename, join } from 'node:path'
import { gunzipSync, gzipSync } from 'node:zlib'

const VERSION = 'v0.4.2' // sync: src/lib/ocr/assets.ts
const ROOT = join(import.meta.dirname, '..')
const OUT = join(ROOT, 'public', 'ocr', 'paddle', VERSION)
const DOWNLOAD = join(OUT, 'download')
const PACKAGE_ROOT = join(ROOT, 'node_modules', '@paddleocr', 'paddleocr-js')
const ORT_ROOT = join(ROOT, 'node_modules', 'onnxruntime-web')
const OCR_ROOT = join(ROOT, 'public', 'ocr')
const LICENSE_ROOT = join(OCR_ROOT, 'paddle', 'licenses')
const MODEL_SHA256: Record<string, string> = {
  'ppocrv5-mobile-det.tar.gz': '635dcb3ad4ee25aa77fbc9d58eb3b0269327c64b0db7ab6b600755d08e6276b0',
  'ppocrv5-mobile-rec.tar.gz': '92b138ed6adfb65f6eefa80d176ebd7802ae3f0783fce2af7225ad939b82405d',
}

interface AssetSpec {
  sourceName: string
  target: string
  contentType: string
  raw: Uint8Array
  committed?: boolean
}

function sha256(bytes: Uint8Array): string {
  return createHash('sha256').update(bytes).digest('hex')
}

function requirePackageVersion(): void {
  const pkg = JSON.parse(readFileSync(join(PACKAGE_ROOT, 'package.json'), 'utf8')) as {
    version?: string
  }
  if (`v${pkg.version}` !== VERSION) {
    throw new Error(`PaddleOCR.js ${pkg.version ?? 'unknown'} does not match ${VERSION}`)
  }
}

function findWorker(): string {
  const dir = join(PACKAGE_ROOT, 'dist', 'assets')
  const matches = readdirSync(dir).filter(
    (name) => name.startsWith('worker-entry-') && name.endsWith('.js'),
  )
  if (matches.length !== 1) {
    throw new Error(`expected one Paddle worker in ${dir}, found ${matches.length}`)
  }
  return join(dir, matches[0])
}

function committedModel(name: string): Uint8Array {
  const file = join(DOWNLOAD, name)
  if (!existsSync(file)) {
    throw new Error(`${file} is missing — see docs/development.md for the pinned model source`)
  }
  const compressed = readFileSync(file)
  if (sha256(compressed) !== MODEL_SHA256[name]) {
    throw new Error(`${file} does not match the pinned official model checksum`)
  }
  return gunzipSync(compressed)
}

function writeThirdPartyLicenses(): void {
  mkdirSync(LICENSE_ROOT, { recursive: true })
  // Apache-2.0 is the license used by PaddleOCR, its models, and OpenCV.js.
  copyFileSync(join(ROOT, 'node_modules', '@techstark', 'opencv-js', 'LICENSE'), join(LICENSE_ROOT, 'Apache-2.0.txt'))
  // The MIT text is identical for js-yaml and onnxruntime-web.
  copyFileSync(join(ROOT, 'node_modules', 'js-yaml', 'LICENSE'), join(LICENSE_ROOT, 'MIT.txt'))
  writeFileSync(
    join(LICENSE_ROOT, 'BSL-1.0.txt'),
    'Boost Software License - Version 1.0 - August 17th, 2003\n\nPermission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute, and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the Software is furnished to do so, all subject to the following:\n\nThe copyright notices in the Software and this entire statement, including the above license grant, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all derivative works of the Software, unless such copies or derivative works are solely in the form of machine-executable object code generated by a source language processor.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n',
  )
}

requirePackageVersion()
mkdirSync(DOWNLOAD, { recursive: true })
writeThirdPartyLicenses()

const specs: AssetSpec[] = [
  {
    sourceName: 'worker.js.gz',
    target: `/ocr/paddle/${VERSION}/worker.js`,
    contentType: 'text/javascript; charset=utf-8',
    raw: readFileSync(findWorker()),
  },
  {
    sourceName: 'ort-wasm-simd-threaded.jsep.wasm.gz',
    target: `/ocr/paddle/${VERSION}/runtime/ort-wasm-simd-threaded.jsep.wasm`,
    contentType: 'application/wasm',
    raw: readFileSync(join(ORT_ROOT, 'dist', 'ort-wasm-simd-threaded.jsep.wasm')),
  },
  {
    sourceName: 'ort-wasm-simd-threaded.jsep.mjs.gz',
    target: `/ocr/paddle/${VERSION}/runtime/ort-wasm-simd-threaded.jsep.mjs`,
    contentType: 'text/javascript; charset=utf-8',
    raw: readFileSync(join(ORT_ROOT, 'dist', 'ort-wasm-simd-threaded.jsep.mjs')),
  },
  {
    sourceName: 'ppocrv5-mobile-det.tar.gz',
    target: `/ocr/paddle/${VERSION}/models/PP-OCRv5_mobile_det.tar`,
    contentType: 'application/octet-stream',
    raw: committedModel('ppocrv5-mobile-det.tar.gz'),
    committed: true,
  },
  {
    sourceName: 'ppocrv5-mobile-rec.tar.gz',
    target: `/ocr/paddle/${VERSION}/models/PP-OCRv5_mobile_rec.tar`,
    contentType: 'application/octet-stream',
    raw: committedModel('ppocrv5-mobile-rec.tar.gz'),
    committed: true,
  },
]

const files = specs.map((spec) => {
  const output = join(DOWNLOAD, spec.sourceName.replace(/\.gz$/u, '.pack'))
  const compressed = spec.committed
    ? readFileSync(join(DOWNLOAD, spec.sourceName))
    : gzipSync(spec.raw, { level: 9 })
  if (!existsSync(output) || !readFileSync(output).equals(compressed)) {
    writeFileSync(output, compressed)
  }
  return {
    source: `/ocr/paddle/${VERSION}/download/${basename(output)}`,
    target: spec.target,
    bytes: statSync(output).size,
    inflatedBytes: spec.raw.byteLength,
    sha256: sha256(compressed),
    contentType: spec.contentType,
  }
})

const manifest = {
  version: VERSION,
  totalBytes: files.reduce((sum, file) => sum + file.bytes, 0),
  files,
}
writeFileSync(join(OUT, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`)
const fallbackFiles = [
  '/ocr/engine/tesseract-client.js',
  '/ocr/engine/tesseract-worker.js',
  '/ocr/engine/tesseract-core.wasm',
  '/ocr/engine/tesseract-core-fallback.wasm',
  '/ocr/models/jpn.traineddata.gz',
  '/ocr/models/eng.traineddata.gz',
].map((path) => [path, statSync(join(ROOT, 'public', path)).size] as const)
const offlineManifest = {
  version: VERSION,
  paddleBytes: manifest.totalBytes,
  totalBytes: manifest.totalBytes + fallbackFiles.reduce((sum, [, bytes]) => sum + bytes, 0),
  files: fallbackFiles,
}
writeFileSync(
  join(OCR_ROOT, 'offline-manifest.json'),
  `${JSON.stringify(offlineManifest, null, 2)}\n`,
)
console.log(
  `copy-paddleocr: ${files.length} Paddle files, ${(manifest.totalBytes / 1048576).toFixed(1)} MB compressed; ${(offlineManifest.totalBytes / 1048576).toFixed(1)} MB full offline OCR pack`,
)
