import { fetchJsonGz } from './fetch-gz'
import type {
  JlptLevel,
  KanjiEntry,
  KanjiWordRow,
  VerbEntry,
  VerbIndexRow,
  VocabEntry,
  VocabIndexRow,
} from './types'

const verbCache = new Map<JlptLevel, Promise<VerbEntry[]>>()
const vocabCache = new Map<JlptLevel, Promise<VocabEntry[]>>()

/**
 * Lazy-loads one JLPT level's verbs. Served as pre-gzipped static files
 * (public/data/jlpt, written by scripts/pack-jlpt.ts) rather than JSON
 * imports — Vite modules carried the pretty-printing plus an inline
 * sourcemap, inflating a 2.9 MB file to a 24 MB dev download.
 */
export function loadVerbLevel(level: JlptLevel): Promise<VerbEntry[]> {
  let cached = verbCache.get(level)
  if (!cached) {
    cached = fetchJsonGz<VerbEntry[]>(`jlpt/verbs-n${level}.json.gz`)
    cached.catch(() => verbCache.delete(level)) // don't cache a failed fetch
    verbCache.set(level, cached)
  }
  return cached
}

export function loadVocabLevel(level: JlptLevel): Promise<VocabEntry[]> {
  let cached = vocabCache.get(level)
  if (!cached) {
    cached = fetchJsonGz<VocabEntry[]>(`jlpt/vocab-n${level}.json.gz`)
    cached.catch(() => vocabCache.delete(level)) // don't cache a failed fetch
    vocabCache.set(level, cached)
  }
  return cached
}

// --- extended tier (level 0: full JMdict beyond the JLPT lists) -------------
// Too large to bundle: generated by scripts/build-extended.ts into
// public/data and fetched on demand. Keep the shard counts in sync with it.
const VERB_EXT_SHARDS = 128
const VOCAB_EXT_SHARDS = 512

let verbExtIndexCache: Promise<VerbIndexRow[]> | null = null

/**
 * The extended verb index as RAW rows — deliberately not materialized into
 * entries (200k objects froze the tab); search them with ext-search.ts.
 */
export function loadVerbExtIndex(): Promise<VerbIndexRow[]> {
  if (!verbExtIndexCache) {
    verbExtIndexCache = fetchJsonGz<VerbIndexRow[]>('verbs-ext/index.json.gz')
    verbExtIndexCache.catch(() => {
      verbExtIndexCache = null // don't cache a failed fetch
    })
  }
  return verbExtIndexCache
}

let vocabExtIndexCache: Promise<VocabIndexRow[]> | null = null

export function loadVocabExtIndex(): Promise<VocabIndexRow[]> {
  if (!vocabExtIndexCache) {
    vocabExtIndexCache = fetchJsonGz<VocabIndexRow[]>('vocab-ext/index.json.gz')
    vocabExtIndexCache.catch(() => {
      vocabExtIndexCache = null // don't cache a failed fetch
    })
  }
  return vocabExtIndexCache
}

/** Loads several JLPT levels, concatenated easiest-first (N5 → N1). */
export async function loadVerbLevels(levels: readonly JlptLevel[]): Promise<VerbEntry[]> {
  const sorted = [...levels].sort((a, b) => b - a)
  const lists = await Promise.all(sorted.map(loadVerbLevel))
  return lists.flat()
}

export async function loadVocabLevels(levels: readonly JlptLevel[]): Promise<VocabEntry[]> {
  const sorted = [...levels].sort((a, b) => b - a)
  const lists = await Promise.all(sorted.map(loadVocabLevel))
  return lists.flat()
}

// --- kanji: two tiers, like the words ---------------------------------------
// One full KANJIDIC2 file was a 400 KB fetch on every detail page. The core
// file (JLPT-listed or frequency-ranked, ~127 KB) covers nearly every char a
// JLPT word contains; the other ~7.8k chars live in 16 codepoint shards
// (~20 KB each) fetched only on a core miss or for Beyond browsing.
// Keep the shard count in sync with scripts/pack-jlpt.ts.
const KANJI_EXT_SHARDS = 16

let kanjiCoreCache: Promise<Record<string, KanjiEntry>> | null = null

export function loadKanjiCore(): Promise<Record<string, KanjiEntry>> {
  if (!kanjiCoreCache) {
    kanjiCoreCache = fetchJsonGz<Record<string, KanjiEntry>>('jlpt/kanji-core.json.gz')
    kanjiCoreCache.catch(() => {
      kanjiCoreCache = null // don't cache a failed fetch
    })
  }
  return kanjiCoreCache
}

const kanjiShardCache = new Map<number, Promise<Record<string, KanjiEntry>>>()

function loadKanjiShard(n: number): Promise<Record<string, KanjiEntry>> {
  let shard = kanjiShardCache.get(n)
  if (!shard) {
    shard = fetchJsonGz<Record<string, KanjiEntry>>(`kanji-ext/words-${n}.json.gz`)
    shard.catch(() => kanjiShardCache.delete(n)) // don't cache a failed fetch
    kanjiShardCache.set(n, shard)
  }
  return shard
}

/**
 * Resolves specific characters: the core file first, ext shards only for
 * the misses. Unknown characters are simply absent from the result.
 */
export async function findKanjiChars(chars: string[]): Promise<Record<string, KanjiEntry>> {
  const core = await loadKanjiCore()
  const out: Record<string, KanjiEntry> = {}
  const missing = new Set<number>()
  for (const c of chars) {
    if (core[c]) out[c] = core[c]
    else missing.add((c.codePointAt(0) ?? 0) % KANJI_EXT_SHARDS)
  }
  if (missing.size > 0) {
    const shards = await Promise.all(
      [...missing].map((n) => loadKanjiShard(n).catch(() => ({}) as Record<string, KanjiEntry>)),
    )
    for (const shard of shards) {
      for (const c of chars) if (!out[c] && shard[c]) out[c] = shard[c]
    }
  }
  return out
}

/** Every beyond-core kanji, merged from all shards — opt-in browsing only. */
export async function loadKanjiExt(): Promise<KanjiEntry[]> {
  const shards = await Promise.all(
    Array.from({ length: KANJI_EXT_SHARDS }, (_, n) => loadKanjiShard(n)),
  )
  return shards.flatMap((shard) => Object.values(shard))
}

// --- "words using this kanji" (precomputed) ----------------------------------
// The kanji detail page's word table, precomputed by scripts/pack-jlpt.ts so
// the page fetches one small codepoint shard instead of every JLPT level
// file (~1.7 MB) just to filter it by character. Keep the shard count in
// sync with that script.
const KANJI_WORDS_SHARDS = 64

const kanjiWordsCache = new Map<number, Promise<Record<string, KanjiWordRow[]>>>()

/** JLPT words whose written form uses the kanji, easiest level first. */
export async function findKanjiWords(char: string): Promise<KanjiWordRow[]> {
  const n = (char.codePointAt(0) ?? 0) % KANJI_WORDS_SHARDS
  let shard = kanjiWordsCache.get(n)
  if (!shard) {
    shard = fetchJsonGz<Record<string, KanjiWordRow[]>>(`kanji-words/${n}.json.gz`)
    shard.catch(() => kanjiWordsCache.delete(n)) // don't cache a failed fetch
    kanjiWordsCache.set(n, shard)
  }
  try {
    return (await shard)[char] ?? []
  } catch {
    return []
  }
}

// --- stroke order (KanjiVG) --------------------------------------------------
// Just the SVG path `d` strings per character, in stroke order, packed into
// 256 codepoint shards (~11 KB each) by scripts/build-strokes.ts — a page
// pays one small shard per distinct kanji it shows strokes for, never the
// whole 2.7 MB dataset. Keep the shard count in sync with that script.
const STROKE_SHARDS = 256

const strokeShardCache = new Map<number, Promise<Record<string, string[]>>>()

/** Stroke paths for one character; undefined when KanjiVG has no data. */
export async function findStrokes(char: string): Promise<string[] | undefined> {
  const n = (char.codePointAt(0) ?? 0) % STROKE_SHARDS
  let shard = strokeShardCache.get(n)
  if (!shard) {
    shard = fetchJsonGz<Record<string, string[]>>(`strokes/${n}.json.gz`)
    shard.catch(() => strokeShardCache.delete(n)) // don't cache a failed fetch
    strokeShardCache.set(n, shard)
  }
  try {
    return (await shard)[char]
  } catch {
    return undefined
  }
}

const verbShardCache = new Map<number, Promise<Record<string, VerbEntry>>>()
const vocabShardCache = new Map<number, Promise<Record<string, VocabEntry>>>()

async function findInShard<T>(
  dir: string,
  shards: number,
  cache: Map<number, Promise<Record<string, T>>>,
  id: string,
): Promise<T | undefined> {
  const n = Number(id) % shards
  if (!Number.isInteger(n) || n < 0) return undefined
  let shard = cache.get(n)
  if (!shard) {
    shard = fetchJsonGz<Record<string, T>>(`${dir}/words-${n}.json.gz`)
    cache.set(n, shard)
  }
  try {
    return (await shard)[id]
  } catch {
    cache.delete(n) // don't cache a failed fetch
    return undefined
  }
}

// --- id → level routing ------------------------------------------------------
// A small map (public/data/jlpt/ids.json.gz, written by pack-jlpt.ts) of every
// JLPT-listed id to its level, per dataset. Detail pages resolve an id with
// exactly one level-file or ext-shard fetch — the old N5→N1 scan made a cold
// deep link to an N1 or Beyond word download every level file (~1.2 MB)
// across five serial round-trips.
type IdLevelFile = Record<'verbs' | 'vocab', Record<string, number[]>>
type IdLevelMaps = { verbs: Map<string, JlptLevel>; vocab: Map<string, JlptLevel> }

let idLevelCache: Promise<IdLevelMaps | null> | null = null

function loadIdLevels(): Promise<IdLevelMaps | null> {
  idLevelCache ??= fetchJsonGz<IdLevelFile>('jlpt/ids.json.gz')
    .then((file) => {
      const toMap = (levels: Record<string, number[]>) => {
        const m = new Map<string, JlptLevel>()
        for (const [lvl, ids] of Object.entries(levels)) {
          for (const id of ids) m.set(String(id), Number(lvl) as JlptLevel)
        }
        return m
      }
      return { verbs: toMap(file.verbs), vocab: toMap(file.vocab) }
    })
    .catch(() => {
      idLevelCache = null // a transient failure must not pin the slow path
      return null // …but THIS call still falls back to the level scan
    })
  return idLevelCache
}

/** Finds one verb by id: one routed fetch via the id map when available. */
export async function findVerb(id: string): Promise<VerbEntry | undefined> {
  const idx = await loadIdLevels()
  if (idx) {
    const level = idx.verbs.get(id)
    if (level === undefined) return findInShard('verbs-ext', VERB_EXT_SHARDS, verbShardCache, id)
    return (await loadVerbLevel(level)).find((v) => v.id === id)
  }
  for (const level of [5, 4, 3, 2, 1] as const) {
    const verbs = await loadVerbLevel(level)
    const hit = verbs.find((v) => v.id === id)
    if (hit) return hit
  }
  return findInShard('verbs-ext', VERB_EXT_SHARDS, verbShardCache, id)
}

export async function findVocab(id: string): Promise<VocabEntry | undefined> {
  const idx = await loadIdLevels()
  if (idx) {
    const level = idx.vocab.get(id)
    if (level === undefined) return findInShard('vocab-ext', VOCAB_EXT_SHARDS, vocabShardCache, id)
    return (await loadVocabLevel(level)).find((v) => v.id === id)
  }
  for (const level of [5, 4, 3, 2, 1] as const) {
    const words = await loadVocabLevel(level)
    const hit = words.find((v) => v.id === id)
    if (hit) return hit
  }
  return findInShard('vocab-ext', VOCAB_EXT_SHARDS, vocabShardCache, id)
}
