import { fetchJsonGz } from './fetch-gz'
import type {
  JlptLevel,
  KanjiEntry,
  VerbEntry,
  VerbIndexRow,
  VocabEntry,
  VocabIndexRow,
} from './types'

const verbCache = new Map<JlptLevel, Promise<VerbEntry[]>>()
const vocabCache = new Map<JlptLevel, Promise<VocabEntry[]>>()

/**
 * Lazy-loads one JLPT level's verbs. Served as pre-gzipped static files
 * (public/data/jlpt, written by scripts/pack-jlpt.ts) rather than JSON
 * imports — Vite modules carried the pretty-printing plus an inline
 * sourcemap, inflating a 2.9 MB file to a 24 MB dev download.
 */
export function loadVerbLevel(level: JlptLevel): Promise<VerbEntry[]> {
  let cached = verbCache.get(level)
  if (!cached) {
    cached = fetchJsonGz<VerbEntry[]>(`jlpt/verbs-n${level}.json.gz`)
    verbCache.set(level, cached)
  }
  return cached
}

export function loadVocabLevel(level: JlptLevel): Promise<VocabEntry[]> {
  let cached = vocabCache.get(level)
  if (!cached) {
    cached = fetchJsonGz<VocabEntry[]>(`jlpt/vocab-n${level}.json.gz`)
    vocabCache.set(level, cached)
  }
  return cached
}

// --- extended tier (level 0: full JMdict beyond the JLPT lists) -------------
// Too large to bundle: generated by scripts/build-extended.ts into
// public/data and fetched on demand. Keep the shard counts in sync with it.
const VERB_EXT_SHARDS = 32
const VOCAB_EXT_SHARDS = 128

let verbExtIndexCache: Promise<VerbIndexRow[]> | null = null

/**
 * The extended verb index as RAW rows — deliberately not materialized into
 * entries (200k objects froze the tab); search them with ext-search.ts.
 */
export function loadVerbExtIndex(): Promise<VerbIndexRow[]> {
  verbExtIndexCache ??= fetchJsonGz<VerbIndexRow[]>('verbs-ext/index.json.gz')
  return verbExtIndexCache
}

let vocabExtIndexCache: Promise<VocabIndexRow[]> | null = null

export function loadVocabExtIndex(): Promise<VocabIndexRow[]> {
  vocabExtIndexCache ??= fetchJsonGz<VocabIndexRow[]>('vocab-ext/index.json.gz')
  return vocabExtIndexCache
}

/** Loads several JLPT levels, concatenated easiest-first (N5 → N1). */
export async function loadVerbLevels(levels: readonly JlptLevel[]): Promise<VerbEntry[]> {
  const sorted = [...levels].sort((a, b) => b - a)
  const lists = await Promise.all(sorted.map(loadVerbLevel))
  return lists.flat()
}

export async function loadVocabLevels(levels: readonly JlptLevel[]): Promise<VocabEntry[]> {
  const sorted = [...levels].sort((a, b) => b - a)
  const lists = await Promise.all(sorted.map(loadVocabLevel))
  return lists.flat()
}

let kanjiCache: Promise<Record<string, KanjiEntry>> | null = null

export function loadKanji(): Promise<Record<string, KanjiEntry>> {
  kanjiCache ??= fetchJsonGz<Record<string, KanjiEntry>>('jlpt/kanji.json.gz')
  return kanjiCache
}

const verbShardCache = new Map<number, Promise<Record<string, VerbEntry>>>()
const vocabShardCache = new Map<number, Promise<Record<string, VocabEntry>>>()

async function findInShard<T>(
  dir: string,
  shards: number,
  cache: Map<number, Promise<Record<string, T>>>,
  id: string,
): Promise<T | undefined> {
  const n = Number(id) % shards
  if (!Number.isInteger(n) || n < 0) return undefined
  let shard = cache.get(n)
  if (!shard) {
    shard = fetchJsonGz<Record<string, T>>(`${dir}/words-${n}.json.gz`)
    cache.set(n, shard)
  }
  try {
    return (await shard)[id]
  } catch {
    cache.delete(n) // don't cache a failed fetch
    return undefined
  }
}

/** Finds one verb by id: JLPT levels first, then the extended shards. */
export async function findVerb(id: string): Promise<VerbEntry | undefined> {
  for (const level of [5, 4, 3, 2, 1] as const) {
    const verbs = await loadVerbLevel(level)
    const hit = verbs.find((v) => v.id === id)
    if (hit) return hit
  }
  return findInShard('verbs-ext', VERB_EXT_SHARDS, verbShardCache, id)
}

export async function findVocab(id: string): Promise<VocabEntry | undefined> {
  for (const level of [5, 4, 3, 2, 1] as const) {
    const words = await loadVocabLevel(level)
    const hit = words.find((v) => v.id === id)
    if (hit) return hit
  }
  return findInShard('vocab-ext', VOCAB_EXT_SHARDS, vocabShardCache, id)
}
